name: Build single file pyinstaller

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.9]

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller pymongo

    - name: Build executable
      run: |
        cd src
        pyinstaller --onefile main.py

    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: executable-${{ matrix.os }}
        path: |
          src/dist/main
          src/dist/main.exe
